name: Run Script

on:
  push:
    paths:
      - 'PL/example2/question_bank.md'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  
          
      - name: Run script and capture output
        id: run_script
        run: |
          chmod +x PL/example2/generate_file.py
          python PL/example2/generate_file.py > generated_files.txt
          cat generated_files.txt  # Optional: Display the captured output

      - name: Delete existing generated files
        run: |
          while read -r line; do
            if [ -f "$line" ]; then
            rm -f "$line"
            echo "Deleted existing file: $line"
            elif [ -d "$line" ]; then
            rm -rf "$line"
            echo "Deleted existing directory: $line"
            else
            echo "No existing file or directory found: $line"
            fi
          done < generated_files.txt
          
      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: PL/example2/question*/

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: generated-files
          merge-multiple: true
      - name: Display structure of downloaded files
        run:  ls -R /home/runner/work/pl-scripts/pl-scripts

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            
            git commit -m "Add processed artifacts"
            git push --force  # Force push to ensure changes are applied
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      
 
