name: Run Script

on:
  push:
    paths:
      - 'PL/example2/question_bank.md'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        run: |
          chmod +x PL/example2/generate_file.py
          python PL/example2/generate_file.py
          
      - name: Upload generated files
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: PL/example2/question*/

  download-and-verify:
    runs-on: ubuntu-latest
    needs: run-script  # Ensure this job runs after the 'run-script' job

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: PL/example2/artifacts  # Specify the directory where artifacts will be saved

      - name: Display structure of downloaded files
        run: ls -R PL/example2/artifacts  # List all files and directories recursively
