name: Run Script

on:
  push:
    paths:
      - 'PL/example2/question_bank.md'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  
          
      - name: Run script and capture output
        id: run_script
        run: |
          chmod +x PL/example2/generate_file.py
          python PL/example2/generate_file.py > generated_files.txt
          cat generated_files.txt  # Optional: Display the captured output

      - name: Upload generated files (question folders)
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: question_*/  # Uploads all question folders

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: generated-files
          path: .  # Download artifacts into the root folder
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R question_*/

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add processed artifacts"
            git push --force  # Force push to ensure changes are applied
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}